/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LinhaDoTempoAbRouteImport } from './routes/linha-do-tempo-ab'
import { Route as PrototipoLbsRouteImport } from './routes/prototipo-lbs'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as ALbsIndexRouteImport } from './routes/a-lbs.index'
import { Route as ALbsHistoriaRouteImport } from './routes/a-lbs.historia'
import { Route as AtuacaoIndexRouteImport } from './routes/atuacao.index'
import { Route as AtuacaoDireitoTrabalhistaRouteImport } from './routes/atuacao.direito-trabalhista'
import { Route as EquipeIndexRouteImport } from './routes/equipe.index'
import { Route as EquipeSlugRouteImport } from './routes/equipe.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhaDoTempoAbRoute = LinhaDoTempoAbRouteImport.update({
  id: '/linha-do-tempo-ab',
  path: '/linha-do-tempo-ab',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototipoLbsRoute = PrototipoLbsRouteImport.update({
  id: '/prototipo-lbs',
  path: '/prototipo-lbs',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ALbsIndexRoute = ALbsIndexRouteImport.update({
  id: '/a-lbs/',
  path: '/a-lbs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ALbsHistoriaRoute = ALbsHistoriaRouteImport.update({
  id: '/a-lbs/historia',
  path: '/a-lbs/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const AtuacaoIndexRoute = AtuacaoIndexRouteImport.update({
  id: '/atuacao/',
  path: '/atuacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtuacaoDireitoTrabalhistaRoute =
  AtuacaoDireitoTrabalhistaRouteImport.update({
    id: '/atuacao/direito-trabalhista',
    path: '/atuacao/direito-trabalhista',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipeIndexRoute = EquipeIndexRouteImport.update({
  id: '/equipe/',
  path: '/equipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeSlugRoute = EquipeSlugRouteImport.update({
  id: '/equipe/$slug',
  path: '/equipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/linha-do-tempo-ab': typeof LinhaDoTempoAbRoute
  '/prototipo-lbs': typeof PrototipoLbsRoute
  '/solucoes': typeof SolucoesRoute
  '/a-lbs/historia': typeof ALbsHistoriaRoute
  '/atuacao/direito-trabalhista': typeof AtuacaoDireitoTrabalhistaRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/a-lbs/': typeof ALbsIndexRoute
  '/atuacao/': typeof AtuacaoIndexRoute
  '/equipe/': typeof EquipeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/linha-do-tempo-ab': typeof LinhaDoTempoAbRoute
  '/prototipo-lbs': typeof PrototipoLbsRoute
  '/solucoes': typeof SolucoesRoute
  '/a-lbs/historia': typeof ALbsHistoriaRoute
  '/atuacao/direito-trabalhista': typeof AtuacaoDireitoTrabalhistaRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/a-lbs': typeof ALbsIndexRoute
  '/atuacao': typeof AtuacaoIndexRoute
  '/equipe': typeof EquipeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/linha-do-tempo-ab': typeof LinhaDoTempoAbRoute
  '/prototipo-lbs': typeof PrototipoLbsRoute
  '/solucoes': typeof SolucoesRoute
  '/a-lbs/historia': typeof ALbsHistoriaRoute
  '/atuacao/direito-trabalhista': typeof AtuacaoDireitoTrabalhistaRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/a-lbs/': typeof ALbsIndexRoute
  '/atuacao/': typeof AtuacaoIndexRoute
  '/equipe/': typeof EquipeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/linha-do-tempo-ab'
    | '/prototipo-lbs'
    | '/solucoes'
    | '/a-lbs/historia'
    | '/atuacao/direito-trabalhista'
    | '/equipe/$slug'
    | '/a-lbs/'
    | '/atuacao/'
    | '/equipe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/linha-do-tempo-ab'
    | '/prototipo-lbs'
    | '/solucoes'
    | '/a-lbs/historia'
    | '/atuacao/direito-trabalhista'
    | '/equipe/$slug'
    | '/a-lbs'
    | '/atuacao'
    | '/equipe'
  id:
    | '__root__'
    | '/'
    | '/linha-do-tempo-ab'
    | '/prototipo-lbs'
    | '/solucoes'
    | '/a-lbs/historia'
    | '/atuacao/direito-trabalhista'
    | '/equipe/$slug'
    | '/a-lbs/'
    | '/atuacao/'
    | '/equipe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinhaDoTempoAbRoute: typeof LinhaDoTempoAbRoute
  PrototipoLbsRoute: typeof PrototipoLbsRoute
  SolucoesRoute: typeof SolucoesRoute
  ALbsHistoriaRoute: typeof ALbsHistoriaRoute
  AtuacaoDireitoTrabalhistaRoute: typeof AtuacaoDireitoTrabalhistaRoute
  EquipeSlugRoute: typeof EquipeSlugRoute
  ALbsIndexRoute: typeof ALbsIndexRoute
  AtuacaoIndexRoute: typeof AtuacaoIndexRoute
  EquipeIndexRoute: typeof EquipeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linha-do-tempo-ab': {
      id: '/linha-do-tempo-ab'
      path: '/linha-do-tempo-ab'
      fullPath: '/linha-do-tempo-ab'
      preLoaderRoute: typeof LinhaDoTempoAbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototipo-lbs': {
      id: '/prototipo-lbs'
      path: '/prototipo-lbs'
      fullPath: '/prototipo-lbs'
      preLoaderRoute: typeof PrototipoLbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-lbs/': {
      id: '/a-lbs/'
      path: '/a-lbs'
      fullPath: '/a-lbs/'
      preLoaderRoute: typeof ALbsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-lbs/historia': {
      id: '/a-lbs/historia'
      path: '/a-lbs/historia'
      fullPath: '/a-lbs/historia'
      preLoaderRoute: typeof ALbsHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao/': {
      id: '/atuacao/'
      path: '/atuacao'
      fullPath: '/atuacao/'
      preLoaderRoute: typeof AtuacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao/direito-trabalhista': {
      id: '/atuacao/direito-trabalhista'
      path: '/atuacao/direito-trabalhista'
      fullPath: '/atuacao/direito-trabalhista'
      preLoaderRoute: typeof AtuacaoDireitoTrabalhistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/': {
      id: '/equipe/'
      path: '/equipe'
      fullPath: '/equipe/'
      preLoaderRoute: typeof EquipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/$slug': {
      id: '/equipe/$slug'
      path: '/equipe/$slug'
      fullPath: '/equipe/$slug'
      preLoaderRoute: typeof EquipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinhaDoTempoAbRoute: LinhaDoTempoAbRoute,
  PrototipoLbsRoute: PrototipoLbsRoute,
  SolucoesRoute: SolucoesRoute,
  ALbsHistoriaRoute: ALbsHistoriaRoute,
  AtuacaoDireitoTrabalhistaRoute: AtuacaoDireitoTrabalhistaRoute,
  EquipeSlugRoute: EquipeSlugRoute,
  ALbsIndexRoute: ALbsIndexRoute,
  AtuacaoIndexRoute: AtuacaoIndexRoute,
  EquipeIndexRoute: EquipeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
