/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototipoLbsRouteImport } from './routes/prototipo-lbs'
import { Route as AtuacaoIndexRouteImport } from './routes/atuacao.index'
import { Route as AtuacaoDireitoTrabalhistaRouteImport } from './routes/atuacao.direito-trabalhista'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototipoLbsRoute = PrototipoLbsRouteImport.update({
  id: '/prototipo-lbs',
  path: '/prototipo-lbs',
  getParentRoute: () => rootRouteImport,
} as any)
const AtuacaoIndexRoute = AtuacaoIndexRouteImport.update({
  id: '/atuacao/',
  path: '/atuacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtuacaoDireitoTrabalhistaRoute =
  AtuacaoDireitoTrabalhistaRouteImport.update({
    id: '/atuacao/direito-trabalhista',
    path: '/atuacao/direito-trabalhista',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prototipo-lbs': typeof PrototipoLbsRoute
  '/atuacao/direito-trabalhista': typeof AtuacaoDireitoTrabalhistaRoute
  '/atuacao/': typeof AtuacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prototipo-lbs': typeof PrototipoLbsRoute
  '/atuacao/direito-trabalhista': typeof AtuacaoDireitoTrabalhistaRoute
  '/atuacao': typeof AtuacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prototipo-lbs': typeof PrototipoLbsRoute
  '/atuacao/direito-trabalhista': typeof AtuacaoDireitoTrabalhistaRoute
  '/atuacao/': typeof AtuacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/prototipo-lbs' | '/atuacao/direito-trabalhista' | '/atuacao/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prototipo-lbs' | '/atuacao/direito-trabalhista' | '/atuacao'
  id:
    | '__root__'
    | '/'
    | '/prototipo-lbs'
    | '/atuacao/direito-trabalhista'
    | '/atuacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrototipoLbsRoute: typeof PrototipoLbsRoute
  AtuacaoDireitoTrabalhistaRoute: typeof AtuacaoDireitoTrabalhistaRoute
  AtuacaoIndexRoute: typeof AtuacaoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototipo-lbs': {
      id: '/prototipo-lbs'
      path: '/prototipo-lbs'
      fullPath: '/prototipo-lbs'
      preLoaderRoute: typeof PrototipoLbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao/': {
      id: '/atuacao/'
      path: '/atuacao'
      fullPath: '/atuacao/'
      preLoaderRoute: typeof AtuacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao/direito-trabalhista': {
      id: '/atuacao/direito-trabalhista'
      path: '/atuacao/direito-trabalhista'
      fullPath: '/atuacao/direito-trabalhista'
      preLoaderRoute: typeof AtuacaoDireitoTrabalhistaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrototipoLbsRoute: PrototipoLbsRoute,
  AtuacaoDireitoTrabalhistaRoute: AtuacaoDireitoTrabalhistaRoute,
  AtuacaoIndexRoute: AtuacaoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
