/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtuacaoRouteImport } from './routes/atuacao'
import { Route as PrototipoLbsRouteImport } from './routes/prototipo-lbs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtuacaoRoute = AtuacaoRouteImport.update({
  id: '/atuacao',
  path: '/atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototipoLbsRoute = PrototipoLbsRouteImport.update({
  id: '/prototipo-lbs',
  path: '/prototipo-lbs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atuacao': typeof AtuacaoRoute
  '/prototipo-lbs': typeof PrototipoLbsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atuacao': typeof AtuacaoRoute
  '/prototipo-lbs': typeof PrototipoLbsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atuacao': typeof AtuacaoRoute
  '/prototipo-lbs': typeof PrototipoLbsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atuacao' | '/prototipo-lbs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atuacao' | '/prototipo-lbs'
  id: '__root__' | '/' | '/atuacao' | '/prototipo-lbs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtuacaoRoute: typeof AtuacaoRoute
  PrototipoLbsRoute: typeof PrototipoLbsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao': {
      id: '/atuacao'
      path: '/atuacao'
      fullPath: '/atuacao'
      preLoaderRoute: typeof AtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototipo-lbs': {
      id: '/prototipo-lbs'
      path: '/prototipo-lbs'
      fullPath: '/prototipo-lbs'
      preLoaderRoute: typeof PrototipoLbsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtuacaoRoute: AtuacaoRoute,
  PrototipoLbsRoute: PrototipoLbsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
